[build]
  command = "npm run build"
  publish = "build/"

# Redirecionamentos, headers, etc.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [build]
  command = "npm run build && npm run export"
  publish = "out"